/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bank.Simulator;

import org.junit.Test;

import Banksim.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
